import Head from "next/head";

// MUI layout components
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

// MUI element components
import Typography from '@mui/material/Typography';

export default function Home() {
  return (
    <>
      <Head>
        <title>MUI intro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth="md" sx={{ background: '#cccccc' }}>
          <Box sx={{ my: 4 }}>
            <Typography variant="h2" component="h2">
              MUI looks good.
            </Typography>
            <Typography variant="p" component="p">
              You can perhaps see why this is a popular package.
            </Typography>   
          </Box>
        </Container>
      </main>
    </>
  );
}
